### PR TITLE
Update old url

### PR DESCRIPTION
**Pull request by jneidel**
/helios64/install throws a 404

/helios64/install -> /helios64/install/preliminary

### CODE REVIEW

**Comment by Siecje** [comment]
https://wiki.kobol.io/helios64/preliminary/ also throws a 404.

These links in the sidebar also throw 404s.

https://wiki.kobol.io/helios64/emmc/
https://wiki.kobol.io/helios64/sdcard/
https://wiki.kobol.io/helios64/transfer/

**Comment by jneidel** [comment]
@Siecje 

> https://wiki.kobol.io/helios64/preliminary/
> https://wiki.kobol.io/helios64/emmc/
> https://wiki.kobol.io/helios64/sdcard/
> https://wiki.kobol.io/helios64/transfer/

Where are these supposed to be?
I greped all of the docs and these are not used anywhere.
 
> These links in the sidebar also throw 404s.

No, sidebar is fine.

**Comment by Siecje** [comment]
I can't find the 404 links anymore.

**Comment by g-provost** [comment]
Thanks for spotting that, forgot to update this url link once we moved some of the pages under an install folder.

**Pull request merged**
